---
instance_groups:
- name: myrole
  jobs:
  - name: tor
    release: tor
    properties:
      bosh_containerization:
        run:
          foo: x

variables:
- name: admin_password
  type: password
  options:
    internal: true
    description: "foo"
- name: default_ca
  type: certificate
  options:
    secret: true
    is_ca: true
    common_name: ca
    internal: true
    description: "foo"
