---
instance_groups:
- name: myrole
  jobs:
  - name: tor
    release: tor
    properties:
      bosh_containerization:
        run:
          foo: x
        ports:
        - name: tcp-route
          protocol: TCP
          count-configurable: true
          internal: 20000-20002
          public: true
          max: 30
