---
instance_groups:
- name: some-group
  jobs:
  - name: tor
    release: tor
    properties:
      bosh_containerization:
        colocated_containers:
        - colocated
        run:
          memory: 128
          scaling:
            min: 1
            max: 1
          volumes:
          - path: /mnt/shared-data
            type: emptyDir
            tag: shared-data

- name: colocated
  type: colocated-container
  jobs:
  - name: tor
    release: tor
    properties:
      bosh_containerization:
        run:
          memory: 128
          scaling:
            min: 1
            max: 1
          volumes:
          - path: /mnt/shared-data
            type: emptyDir
            tag: shared-data
